name: std-release

on:
  push:
    paths:
      - 'std/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Prepare files
        run: |
          mkdir -p released
          cp -r std/ released/std/

      - name: Release std
        uses: softprops/action-gh-release@v1
        with:
          tag_name: std-${{ github.run_number }}
          name: std library release
          files: |
            released/*
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
